### PR TITLE
Allow custom JobPaths in SlurmExecutor

### PR DESCRIPTION
**Pull request by hemildesai**
Addresses #12

### CODE REVIEW

**Comment by Kipok** [comment]
Thanks! I feel that the current way is maybe not the most flexible, e.g. it doesn't allow us to put logs inside a subfolder or to have different format for sbatch/srun logs. Would it be better if instead of custom_pattern Executor would accept a custom JobPaths class (that if not supplied defaults to the current one)? That way we can inherit from the current one and override whatever functions we want to customize and then just provide that to the executor

**Comment by hemildesai** [comment]
> Thanks! I feel that the current way is maybe not the most flexible, e.g. it doesn't allow us to put logs inside a subfolder or to have different format for sbatch/srun logs. Would it be better if instead of custom_pattern Executor would accept a custom JobPaths class (that if not supplied defaults to the current one)? That way we can inherit from the current one and override whatever functions we want to customize and then just provide that to the executor

Yeah that works too, I'll update the PR to have a custom JobPaths.

**Comment by hemildesai** [comment]
@Kipok Updated in https://github.com/NVIDIA/NeMo-Run/pull/22/commits/65bd92fe7499a974d33daa831bc0fdf0ce4631ed

**Review by Kipok — APPROVED** [review]
Thanks!

**Pull request merged**
